[package]
name = "libbpf-rs"
description = "libbpf-rs is a safe, idiomatic, and opinionated wrapper around libbpf-sys"
repository = "https://github.com/libbpf/libbpf-rs"
homepage = "https://github.com/libbpf/libbpf-rs"
readme = "../README.md"
version = "0.19.1"
authors = ["Daniel Xu <dxu@dxuuu.xyz>"]
edition = "2021"
rust-version = "1.58"
license = "LGPL-2.1 OR BSD-2-Clause"
keywords = ["bpf", "ebpf", "libbpf"]

[badges]
maintenance = { status = "actively-developed" }

[features]
# When turned on, link against system-installed libbpf instead of building
# and linking against vendored libbpf sources
novendor = ["libbpf-sys/novendor"]
static = ["libbpf-sys/static"]

[dependencies]
bitflags = "1.3"
lazy_static = "1.4"
libbpf-sys = { version = "1.1.1" }
nix = { version = "0.24", default-features = false, features = ["net", "user"] }
num_enum = "0.5"
strum_macros = "0.23"
thiserror = "1.0"
vsprintf = "2.0"

[dev-dependencies]
libc = "0.2"
log = "0.4.4"
plain = "0.2.3"
probe = "0.3"
scopeguard = "1.1"
serial_test = "0.5"
tempfile = "3.3"

# A set of unused dependencies that we require to force correct minimum versions
# of transitive dependencies, for cases where our dependencies have incorrect
# dependency specifications themselves.
_cc_unused = { package = "cc", version = "1.0.3" }
_pkg-config_unused = { package = "pkg-config", version = "0.3.3" }
_syn_unused = { package = "syn", version = "0.15.15" }
